///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
    public partial class RxDatabaseRepository : RepoGenBaseFolder
    {
        static RxDatabaseRepository instance = new RxDatabaseRepository();
        RxDatabaseRepositoryFolders.DemoApplicationAppFolder _demoapplication;
        RxDatabaseRepositoryFolders.DepartmentListAppFolder _departmentlist;
        RxDatabaseRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseRepository element repository.
        /// </summary>
        [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public static RxDatabaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseRepository() 
            : base("RxDatabaseRepository", "/", null, 0, false, "7ed330c8-5668-4cfa-9ca9-402c4c23b7e2", ".\\RepositoryImages\\RxDatabaseRepository7ed330c8.rximgres")
        {
            _demoapplication = new RxDatabaseRepositoryFolders.DemoApplicationAppFolder(this);
            _departmentlist = new RxDatabaseRepositoryFolders.DepartmentListAppFolder(this);
            _explorer = new RxDatabaseRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

        string _selGender = "rdbMale";

        /// <summary>
        /// Gets or sets the value of variable selGender.
        /// </summary>
        [TestVariable("f63fa448-a002-4de4-ba8d-fda26ab9a4d6")]
        public string selGender
        {
            get { return _selGender; }
            set { _selGender = value; }
        }

        string _lstDepartment = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable lstDepartment.
        /// </summary>
        [TestVariable("60f2067f-c3b5-4687-aec3-b13cba8a934a")]
        public string lstDepartment
        {
            get { return _lstDepartment; }
            set { _lstDepartment = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApplication folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public virtual RxDatabaseRepositoryFolders.DemoApplicationAppFolder DemoApplication
        {
            get { return _demoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public virtual RxDatabaseRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("7481e5c2-bc4e-4fcc-8139-950e46315eb3")]
        public virtual RxDatabaseRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDatabaseRepositoryFolders
    {
        /// <summary>
        /// The DemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public partial class DemoApplicationAppFolder : RepoGenBaseFolder
        {
            RxDatabaseRepositoryFolders.DatabaseTabFolder _databasetab;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _btnexitInfo;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _pagetablistInfo;
            RepoItemInfo _text1001Info;

            /// <summary>
            /// Creates a new DemoApplication  folder.
            /// </summary>
            public DemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "90b14745-bf25-4b07-9bb2-d31f69970826", "")
            {
                _databasetab = new RxDatabaseRepositoryFolders.DatabaseTabFolder(this);
                _databaseInfo = new RepoItemInfo(this, "Database", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "34b9f228-153b-44b4-ae34-1e2747592b0f");
                _btnexitInfo = new RepoItemInfo(this, "BtnExit", "button[@controlname='RxButtonExit']", 30000, null, "02058d54-efaf-4a1d-b09d-9d7d8538364d");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "tabpagelist[@controlname='RxTabcontrol']/?/?/tabpage[@accessiblename='Test database']", 30000, null, "b6aa182f-cb17-40b0-8d21-3fbc94dc7f78");
                _pagetablistInfo = new RepoItemInfo(this, "PageTabList", "?/?/tabpagelist[@accessiblename='']", 30000, null, "d0a649de-55af-4934-b807-3c639cbb660d");
                _text1001Info = new RepoItemInfo(this, "Text1001", ".//combobox[@controlname='cmbDepartment']/text[@controlid='1001']", 30000, null, "8f81b2d8-fb6a-4ac7-aec6-32849f220ecf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual Ranorex.TabPage Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The BtnExit item.
            /// </summary>
            [RepositoryItem("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual Ranorex.Button BtnExit
            {
                get
                {
                    return _btnexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnExit item info.
            /// </summary>
            [RepositoryItemInfo("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual RepoItemInfo BtnExitInfo
            {
                get
                {
                    return _btnexitInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("b6aa182f-cb17-40b0-8d21-3fbc94dc7f78")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("b6aa182f-cb17-40b0-8d21-3fbc94dc7f78")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The PageTabList item.
            /// </summary>
            [RepositoryItem("d0a649de-55af-4934-b807-3c639cbb660d")]
            public virtual Ranorex.TabPageList PageTabList
            {
                get
                {
                    return _pagetablistInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The PageTabList item info.
            /// </summary>
            [RepositoryItemInfo("d0a649de-55af-4934-b807-3c639cbb660d")]
            public virtual RepoItemInfo PageTabListInfo
            {
                get
                {
                    return _pagetablistInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("8f81b2d8-fb6a-4ac7-aec6-32849f220ecf")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("8f81b2d8-fb6a-4ac7-aec6-32849f220ecf")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The DatabaseTab folder.
            /// </summary>
            [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RxDatabaseRepositoryFolders.DatabaseTabFolder DatabaseTab
            {
                get { return _databasetab; }
            }
        }

        /// <summary>
        /// The DatabaseTabFolder folder.
        /// </summary>
        [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
        public partial class DatabaseTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _selectmaleInfo;
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _counterentriesInfo;
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;
            RepoItemInfo _cmbdepartmentInfo;
            RepoItemInfo _rdbfemaleInfo;

            /// <summary>
            /// Creates a new DatabaseTab  folder.
            /// </summary>
            public DatabaseTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTab", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "6634980e-930f-41f9-a6d0-229595c55fed", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "ee66a06e-163b-42b6-8abc-248006bf88ab");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", 30000, null, "305b1e85-498e-4d07-9051-6cd79362827e");
                _selectmaleInfo = new RepoItemInfo(this, "SelectMale", "?/?/radiobutton[@controltext=$selGender]", 30000, null, "a47a714c-11a3-4925-b181-0c2445fd1e45");
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "combobox[@controlname='cmbDepartment']/button", 30000, null, "33397b0b-43c6-4daa-99a2-c7853656f16f");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", 30000, null, "0716c660-ce8c-4fb8-a033-a58ae01bc4fa");
                _counterentriesInfo = new RepoItemInfo(this, "CounterEntries", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "2580fade-1b69-498e-a86e-74c7c8e8be71");
                _txtfirstnameInfo = new RepoItemInfo(this, "TxtFirstName", "text[@controlname='txtFirstName']", 30000, null, "0d05d6f6-bfd5-483d-b674-19b41011e932");
                _txtlastnameInfo = new RepoItemInfo(this, "TxtLastName", "text[@controlname='txtLastName']", 30000, null, "518edc1c-ee97-41f3-a501-5d4c1f2b12e5");
                _cmbdepartmentInfo = new RepoItemInfo(this, "CmbDepartment", "combobox[@controlname='cmbDepartment']", 30000, null, "0e6f579b-e8b8-43e3-9e8d-281694142d05");
                _rdbfemaleInfo = new RepoItemInfo(this, "RdbFemale", "?/?/radiobutton[@controlname=$selGender]", 30000, null, "7792acd9-3e3b-4d99-845d-21a79e27bc4c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The SelectMale item.
            /// </summary>
            [RepositoryItem("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual Ranorex.RadioButton SelectMale
            {
                get
                {
                    return _selectmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectMale item info.
            /// </summary>
            [RepositoryItemInfo("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual RepoItemInfo SelectMaleInfo
            {
                get
                {
                    return _selectmaleInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The CounterEntries item.
            /// </summary>
            [RepositoryItem("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual Ranorex.Text CounterEntries
            {
                get
                {
                    return _counterentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CounterEntries item info.
            /// </summary>
            [RepositoryItemInfo("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual RepoItemInfo CounterEntriesInfo
            {
                get
                {
                    return _counterentriesInfo;
                }
            }

            /// <summary>
            /// The TxtFirstName item.
            /// </summary>
            [RepositoryItem("0d05d6f6-bfd5-483d-b674-19b41011e932")]
            public virtual Ranorex.Text TxtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("0d05d6f6-bfd5-483d-b674-19b41011e932")]
            public virtual RepoItemInfo TxtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The TxtLastName item.
            /// </summary>
            [RepositoryItem("518edc1c-ee97-41f3-a501-5d4c1f2b12e5")]
            public virtual Ranorex.Text TxtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLastName item info.
            /// </summary>
            [RepositoryItemInfo("518edc1c-ee97-41f3-a501-5d4c1f2b12e5")]
            public virtual RepoItemInfo TxtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }

            /// <summary>
            /// The CmbDepartment item.
            /// </summary>
            [RepositoryItem("0e6f579b-e8b8-43e3-9e8d-281694142d05")]
            public virtual Ranorex.ComboBox CmbDepartment
            {
                get
                {
                    return _cmbdepartmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbDepartment item info.
            /// </summary>
            [RepositoryItemInfo("0e6f579b-e8b8-43e3-9e8d-281694142d05")]
            public virtual RepoItemInfo CmbDepartmentInfo
            {
                get
                {
                    return _cmbdepartmentInfo;
                }
            }

            /// <summary>
            /// The RdbFemale item.
            /// </summary>
            [RepositoryItem("7792acd9-3e3b-4d99-845d-21a79e27bc4c")]
            public virtual Ranorex.RadioButton RdbFemale
            {
                get
                {
                    return _rdbfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbFemale item info.
            /// </summary>
            [RepositoryItemInfo("7792acd9-3e3b-4d99-845d-21a79e27bc4c")]
            public virtual RepoItemInfo RdbFemaleInfo
            {
                get
                {
                    return _rdbfemaleInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;
            RepoItemInfo _developmentInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "57208867-ed11-4ec8-924b-0dc686980a77", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text=$lstDepartment]", 30000, null, "b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3");
                _developmentInfo = new RepoItemInfo(this, "Development", "listitem[@text=$lstDepartment]", 30000, null, "9302ba3c-47d2-422b-b0dd-e22c91391ea4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }

            /// <summary>
            /// The Development item.
            /// </summary>
            [RepositoryItem("9302ba3c-47d2-422b-b0dd-e22c91391ea4")]
            public virtual Ranorex.ListItem Development
            {
                get
                {
                    return _developmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Development item info.
            /// </summary>
            [RepositoryItemInfo("9302ba3c-47d2-422b-b0dd-e22c91391ea4")]
            public virtual RepoItemInfo DevelopmentInfo
            {
                get
                {
                    return _developmentInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("7481e5c2-bc4e-4fcc-8139-950e46315eb3")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtestapp101runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "7481e5c2-bc4e-4fcc-8139-950e46315eb3", "")
            {
                _rxtestapp101runningwindowInfo = new RepoItemInfo(this, "RXTestApp101RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[20]", 30000, null, "2d82c9a1-622f-4374-a971-eea9206c5b71");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7481e5c2-bc4e-4fcc-8139-950e46315eb3")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7481e5c2-bc4e-4fcc-8139-950e46315eb3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RXTestApp101RunningWindow item.
            /// </summary>
            [RepositoryItem("2d82c9a1-622f-4374-a971-eea9206c5b71")]
            public virtual Ranorex.Button RXTestApp101RunningWindow
            {
                get
                {
                    return _rxtestapp101runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RXTestApp101RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("2d82c9a1-622f-4374-a971-eea9206c5b71")]
            public virtual RepoItemInfo RXTestApp101RunningWindowInfo
            {
                get
                {
                    return _rxtestapp101runningwindowInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
